# Configuration file for actionlint (https://github.com/rhysd/actionlint)

config-variables: []

paths:
  .github/workflows/*.yml:
    ignore:
      - 'label "ubuntu-26.04" is unknown'
      - 'constant expression "false" in condition.+'
