name: <ACTION>
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - <FILE>
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - <FILE>
  schedule:
    - cron: "<MIN> <HOUR> * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      build-cmd:    <BUILD>
      install-cmd:  <INSTALL>
      node-version: <NODE>
      repository:   <ACTION>
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: <ACTION>@<VERSION>
