name: <ACTION>@<VERSION>
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - <FILE>
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - <FILE>
  schedule:
    - cron: "<MIN> <HOUR> * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        <FILES>
      build-cmd:    <BUILD>
      install-cmd:  <INSTALL>
      node-version: <NODE>
      repository:   <ACTION>
      version-ref:  <VERSION>
