name: actions/upload-artifact@v4
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-upload-artifact-v4.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-upload-artifact-v4.yml
  schedule:
    - cron: "7 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v4:
    name: v4
    uses: ericcornelissen/reproducing-actions/.github/workflows/reusable-test.yml@main
    with:
      files:        dist/merge/index.js dist/upload/index.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/upload-artifact
      version-ref:  v4
