name: actions/setup-java@v4
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-java-v4.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-java-v4.yml
  schedule:
    - cron: "1 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v4:
    name: v4
    uses: ericcornelissen/reproducing-actions/.github/workflows/reusable-test.yml@reusabe-workflow-usage
    with:
      files:        dist/cleanup/index.js dist/setup/index.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/setup-java
      version-ref:  v4
