name: actions/attest-build-provenance@v1
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest-build-provenance-v1.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-attest-build-provenance-v1.yml
  schedule:
    - cron: "24 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v1:
    name: v1
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             dist/index.js
      build-cmd:         npm run package
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/attest-build-provenance
      version-ref:       v1
