name: actions/setup-python@v5
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-python-v5.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-setup-python-v5.yml
  schedule:
    - cron: "8 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v5:
    name: v5
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/cache-save/index.js dist/setup/index.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/setup-python
      version-ref:  v5
