name: actions/labeler@v5
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-labeler-v5.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-labeler-v5.yml
  schedule:
    - cron: "12 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v5:
    name: v5
    uses: ericcornelissen/reproducing-actions/.github/workflows/reusable-test.yml@main
    with:
      files:        dist/index.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/labeler
      version-ref:  v5
