name: actions/create-github-app-token@v2
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-create-github-app-token-v2.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-create-github-app-token-v2.yml
  schedule:
    - cron: "29 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             dist/main.cjs dist/post.cjs
      build-cmd:         npm run build
      install-cmd:       npm clean-install
      node-version-file: .node-version
      repository:        actions/create-github-app-token
      version-ref:       v2
