name: actions/upload-artifact@v5
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-upload-artifact-v5.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/actions-upload-artifact-v5.yml
  schedule:
    - cron: "37 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/merge/index.js dist/upload/index.js
      build-cmd:    npm run release
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   actions/upload-artifact
      version-ref:  v5
