name: asdf-vm/actions@v4
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/asdf-vm-actions-v4.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/asdf-vm-actions-v4.yml
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             install/main.js plugin-test/main.js plugins-add/main.js setup/main.js
      build-cmd:         pnpm build
      install-cmd: |
        corepack enable
        corepack pnpm install
      node-version-file: .tool-versions
      repository:        asdf-vm/actions
      version-ref:       v4
