name: docker/build-push-action@v6
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-build-push-action-v5.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-build-push-action-v5.yml
  schedule:
    - cron: "21 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/index.js dist/licenses.txt
      build-cmd:    yarn build
      install-cmd:  |
        corepack enable
        yarn install
      node-version: 20.x
      repository:   docker/build-push-action
      version-ref:  v6
