name: docker/build-push-action@v5
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-build-push-action-v5.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-build-push-action-v5.yml
  schedule:
    - cron: "21 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v5:
    name: v5
    uses: ericcornelissen/reproducing-actions/.github/workflows/reusable-test.yml@main
    with:
      files:        dist/index.js
      build-cmd:    yarn build
      install-cmd:  yarn install
      node-version: 20.x
      repository:   docker/build-push-action
      version-ref:  v5
