name: docker/login-action@v3
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-login-action-v3.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/docker-login-action-v3.yml
  schedule:
    - cron: "20 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v3:
    name: v3
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/index.js
      build-cmd:    yarn build
      install-cmd:  |
        corepack enable
        yarn install
      node-version: 20.x
      repository:   docker/login-action
      version-ref:  v3
