name: fastify/github-action-merge-dependabot@v3
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/fastify-github-action-merge-dependabot-v3.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/fastify-github-action-merge-dependabot-v3.yml
  schedule:
    - cron: "28 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             dist/index.js
      build-cmd:         npm run build
      install-cmd:       npm clean-install --ignore-scripts
      node-version-file: .nvmrc
      repository:        fastify/github-action-merge-dependabot
      version-ref:       v3
