name: gitleaks/gitleaks-action@v2
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gitleaks-gitleaks-action-v2.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gitleaks-gitleaks-action-v2.yml
  schedule:
    - cron: "3 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v2:
    name: v2
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:              dist/index.js
      build-cmd:          npx ncc build src/index.js
      install-cmd:        npm clean-install
      node-version-file: .nvmrc
      repository:         gitleaks/gitleaks-action
      version-ref:        v2
