name: google/osv-scanner-action
on:
  pull_request:
    paths:
      - .github/workflows/reusable-docker-image-test.yml
      - .github/workflows/google-osv-scanner-action.yml
  push:
    branches:
      - main
      - google-osv
    paths:
      - .github/workflows/reusable-docker-image-test.yml
      - .github/workflows/google-osv-scanner-action.yml
  schedule:
    - cron: "53 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-docker-image-test.yml
    with:
      dockerfile: goreleaser-action.dockerfile
      image: ghcr.io/google/osv-scanner-action:v2.3.5
      repository: google/osv-scanner
      setup-cmd: >-
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64
        go build -trimpath -ldflags="-s -w"
        -o osv-scanner-action ./cmd/osv-scanner
        &&
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64
        go build -trimpath -ldflags="-s -w"
        -o osv-reporter ./cmd/osv-reporter
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: google/osv-scanner-action@v2.3.5
