name: gradle/actions@v4
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gradle-actions-v4.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/gradle-actions-v4.yml
  schedule:
    - cron: "32 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/**/*.js
      build-cmd: |
        cd sources/
        npm run compile
      install-cmd: |
        cd sources/
        npm clean-install
      node-version: 20
      repository:   gradle/actions
      version-ref:  v4
