name: JamesIves/github-pages-deploy-action@v4
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/JamesIves-github-pages-deploy-action-v4.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/JamesIves-github-pages-deploy-action-v4.yml
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v4:
    name: v4
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:             lib/*.js
      build-cmd:         yarn build
      install-cmd:       yarn install
      node-version-file: .node-version
      repository:        JamesIves/github-pages-deploy-action
      version-ref:       v4
