name: ncipollo/release-action@v1
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/ncipollo-release-action-v1.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/ncipollo-release-action-v1.yml
  schedule:
    - cron: "19 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  v1:
    name: v1
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/index.js
      build-cmd:    npm run build
      install-cmd:  npm install
      node-version: 20.x
      repository:   ncipollo/release-action
      version-ref:  v1
