name: peter-evans/create-pull-request@v7
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/peter-evans-create-pull-request-v7.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/peter-evans-create-pull-request-v7.yml
  schedule:
    - cron: "18 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/790.index.js dist/index.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20.x
      repository:   peter-evans/create-pull-request
      version-ref:  v7
