name: pnpm/action-setup
on:
  pull_request:
    paths:
      - .github/workflows/reusable-node-test.yml
      - .github/workflows/pnpm-action-setup.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-node-test.yml
      - .github/workflows/pnpm-action-setup.yml
  schedule:
    - cron: "51 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-node-test.yml
    with:
      build-cmd:    pnpm run build
      install-cmd:  |
        corepack enable
        corepack prepare pnpm@^8.14.3 --activate
        corepack pnpm install
      repository:   pnpm/action-setup
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4.3.0
