on:
  workflow_call:
    inputs:
      # Setup
      dockerfile:
        required: true
        type: string

      # Target
      repository:
        required: true
        type: string

permissions: read-all

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      repository: ${{ inputs.repository }}
  build:
    name: build ${{ needs.setup.outputs.version }}
    runs-on: ubuntu-24.04
    needs:
      - setup
    env:
      DOCKERFILE: ${{ inputs.dockerfile }}
    steps:
      # Repository setup
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ needs.setup.outputs.version }}
          repository: ${{ inputs.repository }}

      # Environment setup
      - name: Install tooling
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1

      # Check reproducibility
      - name: Build 1
        run: docker build --no-cache --file "$DOCKERFILE" --tag test1 .
      - name: Build 2
        run: docker build --no-cache --file "$DOCKERFILE" --tag test2 .
      - name: Diff images
        run: diffoci diff --semantic docker://test1 docker://test2
