on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
    outputs:
      version:
          value: ${{ jobs.setup.outputs.version }}

permissions: read-all

jobs:
  setup:
    name: setup
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Determine version to reproduce
        id: version
        env:
          REPO: ${{ inputs.repository }}
        run: |
          WORKFLOW=$(echo "${REPO//\//-}.yml" | tr '[:upper:]' '[:lower:]')
          VERSION=$( \
            cat ".github/workflows/$WORKFLOW" \
              | grep -oE '^\s+- uses: [^@]+@v?[^"]*' \
              | sed 's/.*@//' \
          )
          echo "$VERSION"
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"
