# WARNING:
# When using this reusable workflow, provide only trusted values to the input
# `dockerfile`. The design of this workflow requires this input to be embedded
# in scripts, which allows it to be used to build from an arbitrary Dockerfile.

on:
  workflow_call:
    inputs:
      # Reference image
      reference-image:
        required: true
        type: string

      # Setup
      dockerfile:
        required: true
        type: string

      # Target
      repository:
        required: true
        type: string
      version-ref:
        required: true
        type: string

permissions: read-all

jobs:
  build:
    name: Reproducible build
    runs-on: ubuntu-24.04
    steps:
      # Repository setup
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ inputs.version-ref }}
          repository: ${{ inputs.repository }}

      # Environment setup
      - name: Install diffoci
        env:
          DIFFOCI_VERSION: v0.1.6
        run: |
          curl -L https://github.com/reproducible-containers/diffoci/releases/download/${DIFFOCI_VERSION}/diffoci-${DIFFOCI_VERSION}.linux-amd64 -o /usr/local/bin/diffoci
          chmod +x /usr/local/bin/diffoci

      # Original image
      - name: Pull reference image
        env:
          IMAGE: ${{ inputs.reference-image }}
        run: |
          docker pull "$IMAGE"

      # Rebuild
      - name: Build image
        env:
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker build -f "$DOCKERFILE" -t test .

      # Check reproducibility
      - name: Diff images
        env:
          IMAGE_A: ${{ inputs.reference-image }}
        run: |
          diffoci diff --semantic "$IMAGE_A" docker://test
