# WARNING:
# When using this reusable workflow, provide only trusted values to the input
# `dockerfile`. The design of this workflow requires this input to be embedded
# in scripts, which allows it to be used to build from an arbitrary Dockerfile.

on:
  workflow_call:
    inputs:
      # Image coordinates
      image:
        required: true
        type: string

      # Setup
      dockerfile:
        required: true
        type: string

      # Target
      repository:
        required: true
        type: string

permissions: read-all

jobs:
  setup:
    name: setup
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Determine version to reproduce
        id: version
        env:
          REPO: ${{ inputs.repository }}
        run: |
          WORKFLOW=$(echo "${REPO//\//-}.yml" | tr '[:upper:]' '[:lower:]')
          VERSION=$( \
            cat ".github/workflows/$WORKFLOW" \
              | grep -oE '^\s+- uses: [^@]+@v?[^"]*' \
              | sed 's/.*@//' \
          )
          echo "$VERSION"
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"

  build:
    name: Reproducible build
    runs-on: ubuntu-24.04
    needs:
      - setup
    steps:
      # Repository setup
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ needs.setup.outputs.version }}
          repository: ${{ inputs.repository }}

      # Environment setup
      - name: Install diffoci
        env:
          DIFFOCI_VERSION: v0.1.8
        run: |
          gh release download --repo reproducible-containers/diffoci "${DIFFOCI_VERSION}" --pattern "*linux-amd64" --output /usr/local/bin/diffoci
          chmod +x /usr/local/bin/diffoci

      # Original image
      - name: Pull reference image
        env:
          IMAGE: ${{ inputs.image }}:${{ needs.setup.outputs.version }}
        run: |
          docker pull "$IMAGE"

      # Rebuild
      - name: Build image
        env:
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker build -f "$DOCKERFILE" -t test .

      # Check reproducibility
      - name: Diff images
        env:
          IMAGE_A: ${{ inputs.image }}:${{ needs.setup.outputs.version }}
        run: |
          diffoci diff --semantic "$IMAGE_A" docker://test
