name: SonarSource/sonarqube-scan-action@v6
on:
  pull_request:
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/sonarsource-sonarqube-scan-action-v6.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-test.yml
      - .github/workflows/sonarsource-sonarqube-scan-action-v6.yml
  schedule:
    - cron: "35 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-test.yml
    with:
      files:        dist/exec-BTlTa8sL.js dist/index.js dist/install-build-wrapper.js
      build-cmd:    npm run build
      install-cmd:  npm clean-install
      node-version: 20
      repository:   SonarSource/sonarqube-scan-action
      version-ref:  v6
