name: stepci/stepci
on:
  pull_request:
    paths:
      - .github/workflows/reusable-docker-test.yml
      - .github/workflows/stepci-stepci.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-docker-test.yml
      - .github/workflows/stepci-stepci.yml
  schedule:
    - cron: "25 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-test.yml
    with:
      dockerfile:      Dockerfile.action
      repository:      stepci/stepci
      version-ref:     2.8.2
      reference-image: ghcr.io/stepci/stepci:2.8.2
