name: super-linter/super-linter
on:
  pull_request:
    paths:
      - .github/workflows/reusable-docker-image-test.yml
      - .github/workflows/super-linter-super-linter.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/reusable-docker-image-test.yml
      - .github/workflows/super-linter-super-linter.yml
  schedule:
    - cron: "52 1 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  test:
    uses: ./.github/workflows/reusable-docker-image-test.yml
    with:
      build-args: --secret id=GITHUB_TOKEN,src=/tmp/github_token
      dockerfile: Dockerfile
      image: ghcr.io/super-linter/super-linter:v8.6.0
      repository: super-linter/super-linter
  version:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: super-linter/super-linter@v8.6.0
